export const states = [
    { id: '1', name: 'Acre', state: 'AC' },
    { id: '2', name: 'Alagoas', state: 'AL' },
    { id: '3', name: 'Amapá', state: 'AP' },
    { id: '4', name: 'Amazonas', state: 'AM' },
    { id: '5', name: 'Bahia', state: 'BA' },
    { id: '6', name: 'Ceará', state: 'CE' },
    { id: '7', name: 'Distrito Federal', state: 'DF' },
    { id: '8', name: 'Espírito Santo', state: 'ES' },
    { id: '9', name: 'Goiás', state: 'GO' },
    { id: '10', name: 'Maranhão', state: 'MA' },
    { id: '11', name: 'Mato Grosso', state: 'MT' },
    { id: '12', name: 'Mato Grosso do Sul', state: 'MS' },
    { id: '13', name: 'Minas Gerais', state: 'MG' },
    { id: '14', name: 'Pará', state: 'PA' },
    { id: '15', name: 'Paraíba', state: 'PB' },
    { id: '16', name: 'Paraná', state: 'PR' },
    { id: '17', name: 'Pernambuco', state: 'PE' },
    { id: '18', name: 'Piauí', state: 'PI' },
    { id: '19', name: 'Rio de Janeiro', state: 'RJ' },
    { id: '20', name: 'Rio Grande do Norte', state: 'RN' },
    { id: '21', name: 'Rio Grande do Sul', state: 'RS' },
    { id: '22', name: 'Rondônia', state: 'RO' },
    { id: '23', name: 'Roraima', state: 'RR' },
    { id: '24', name: 'Santa Catarina', state: 'SC' },
    { id: '25', name: 'São Paulo', state: 'SP' },
    { id: '26', name: 'Sergipe', state: 'SE' },
    { id: '27', name: 'Tocantins', state: 'TO' },
]

export const city = [
    { id: '1', name: 'Belo Horizonte', state: 'MG' },
    { id: '2', name: 'Brasília', state: 'DF' },
    { id: '3', name: 'Campo Grande', state: 'MS' },
    { id: '4', name: 'Cuiabá', state: 'MT' },
    { id: '5', name: 'Curitiba', state: 'PR' },
    { id: '6', name: 'Florianópolis', state: 'SC' },
    { id: '7', name: 'Goiânia', state: 'GO' },
    { id: '8', name: 'Joinville', state: 'SC' },
    { id: '9', name: 'Londrina', state: 'PR' },
    { id: '10', name: 'Manaus', state: 'AM' },
    { id: '11', name: 'Porto Alegre', state: 'RS' },
    { id: '12', name: 'Recife', state: 'PE' },
    { id: '13', name: 'Rio de Janeiro', state: 'RJ' },
    { id: '14', name: 'Salvador', state: 'BA' },
    { id: '16', name: 'São Gonçalo', state: 'RJ' },
    { id: '17', name: 'São José dos Campos', state: 'SP' },
    { id: '18', name: 'São Luís', state: 'MA' },
    { id: '19', name: 'São Paulo', state: 'SP' },
    { id: '20', name: 'São Vicente', state: 'SP' },
    { id: '21', name: 'Sorocaba', state: 'SP' },
    { id: '22', name: 'Taguatinga', state: 'SP' },
    { id: '23', name: 'Vitória', state: 'ES' },
    { id: '24', name: 'Fortaleza', state: 'CE' },
    { id: '25', name: 'Belém', state: 'PA' },
    { id: '26', name: 'Goiânia', state: 'GO' },
    { id: '27', name: 'Cuiabá', state: 'MT' },
    { id: '28', name: 'Campo Grande', state: 'MS' },
]